### PR TITLE
rewrote the installer to be easier to use

### PR DESCRIPTION
**Pull request by terrymunro**
So this will need some testing but with this install script you can just:

Open a terminal and:
```shell
curl https://raw.githubusercontent.com/dpnova/pynerstat/master/bin/install | bash
```

It will download the latest tarball from github and install dependencies, run setup.

Should also serve as a crude updater too since you can just re-run the script and it checks if your config already exists so that it doesn't overwrite it.

*Note:* If you want to try the script while its still in my branch you can just change the branch in the URL;
```shell
curl https://raw.githubusercontent.com/dpnova/pynerstat/tm_installer/bin/install | bash
```

### CODE REVIEW

**Comment by coinscrow** [comment]
I will test this and the tool during the day, but looks good. Thanks.

**Comment by dpnova** [comment]
```
Attempting to update Twisted plugin cache.
Twisted plugin cache updated successfully.
bash: line 134: SKIP_PROMPTS: unbound variable
Installation failed.
```

Just tried on another machine and got this error.. mean anything to you?

Cheers

**Comment by terrymunro** [comment]
Yeah, I've set -e and -u which means any unbound variables are errors and any error causes the script to end.

This was supposed to fix that:
```[[ -z $SKIP_PROMPTS ]] && SKIP_PROMPTS=```
but I guess it's not working?

I'll fix it and push update.

**Comment by dpnova** [comment]
Looks good now. Cheers!

**Pull request merged**
